# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'jarvisUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys
import os

def resource_path(relative_path):
                try:
                # PyInstaller creates a temp folder and stores path in _MEIPASS
                        base_path = sys._MEIPASS
                except Exception:
                        base_path = os.path.abspath(".")

                return os.path.join(base_path, relative_path)



class Ui_MainWindow(object):
        
        def setupUi(self, MainWindow):
                MainWindow.setObjectName("MainWindow")
                MainWindow.resize(1062, 656)
                self.centralwidget = QtWidgets.QWidget(MainWindow)
                self.centralwidget.setObjectName("centralwidget")
                self.label = QtWidgets.QLabel(self.centralwidget)
                self.label.setGeometry(QtCore.QRect(-4, 0, 1071, 621))
                self.label.setText("")
                self.label.setPixmap(QtGui.QPixmap(resource_path("label4.gif")))
                self.label.setScaledContents(True)
                self.label.setObjectName("label")
                self.label_2 = QtWidgets.QLabel(self.centralwidget)
                self.label_2.setGeometry(QtCore.QRect(830, 470, 231, 141))
                self.label_2.setText("")
                self.label_2.setPixmap(QtGui.QPixmap(resource_path("1625133656678.jpg")))
                self.label_2.setScaledContents(True)
                self.label_2.setObjectName("label_2")
                self.label_3 = QtWidgets.QLabel(self.centralwidget)
                self.label_3.setGeometry(QtCore.QRect(0, -100, 411, 301))
                self.label_3.setText("")
                self.label_3.setPixmap(QtGui.QPixmap(resource_path("label6.gif")))
                self.label_3.setScaledContents(True)
                self.label_3.setObjectName("label_3")
                self.label_4 = QtWidgets.QLabel(self.centralwidget)
                self.label_4.setGeometry(QtCore.QRect(870, 0, 191, 71))
                self.label_4.setText("")
                self.label_4.setPixmap(QtGui.QPixmap(resource_path("1625133656673.jpg")))
                self.label_4.setScaledContents(True)
                self.label_4.setObjectName("label_4")
                self.label_5 = QtWidgets.QLabel(self.centralwidget)
                self.label_5.setGeometry(QtCore.QRect(680, 0, 191, 71))
                self.label_5.setText("")
                self.label_5.setPixmap(QtGui.QPixmap(resource_path("1625133656673.jpg")))
                self.label_5.setScaledContents(True)
                self.label_5.setObjectName("label_5")
                self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
                self.textBrowser.setGeometry(QtCore.QRect(700, 20, 151, 31))
                self.textBrowser.setStyleSheet("background:transparent;\n""color:#a1e1eb;\n""font-size:25px;\n"
        "border-radius:none;")
                self.textBrowser.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
                self.textBrowser.setObjectName("textBrowser")
                self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
                self.textBrowser_2.setGeometry(QtCore.QRect(890, 20, 151, 31))
                self.textBrowser_2.setStyleSheet("background:transparent;\n""color:#a1e1eb;\n""font-size:25px;\n"
        "border-radius:none;")
                self.textBrowser_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
                self.textBrowser_2.setObjectName("textBrowser_2")
                self.label_6 = QtWidgets.QLabel(self.centralwidget)
                self.label_6.setGeometry(QtCore.QRect(120, 520, 151, 81))
                self.label_6.setText("")
                self.label_6.setPixmap(QtGui.QPixmap(resource_path("1625133656657.png")))
                self.label_6.setScaledContents(True)
                self.label_6.setObjectName("label_6")
                self.label_7 = QtWidgets.QLabel(self.centralwidget)
                self.label_7.setGeometry(QtCore.QRect(740, 520, 151, 81))
                self.label_7.setText("")
                self.label_7.setPixmap(QtGui.QPixmap(resource_path("1625133656662.png")))
                self.label_7.setScaledContents(True)
                self.label_7.setObjectName("label_7")
                self.pushButton = QtWidgets.QPushButton(self.centralwidget)
                self.pushButton.setGeometry(QtCore.QRect(130, 540, 131, 51))
                self.pushButton.setStyleSheet("background:transparent;\n"
        "")
                self.pushButton.setText("")
                self.pushButton.setObjectName("pushButton")
                self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
                self.pushButton_2.setGeometry(QtCore.QRect(750, 530, 131, 51))
                self.pushButton_2.setStyleSheet("background:transparent;\n"
        "")
                self.pushButton_2.setText("")
                self.pushButton_2.setObjectName("pushButton_2")
                MainWindow.setCentralWidget(self.centralwidget)
                self.menubar = QtWidgets.QMenuBar(MainWindow)
                self.menubar.setGeometry(QtCore.QRect(0, 0, 1062, 21))
                self.menubar.setObjectName("menubar")
                MainWindow.setMenuBar(self.menubar)
                self.statusbar = QtWidgets.QStatusBar(MainWindow)
                self.statusbar.setObjectName("statusbar")
                MainWindow.setStatusBar(self.statusbar)

                self.retranslateUi(MainWindow)
                QtCore.QMetaObject.connectSlotsByName(MainWindow)

        def retranslateUi(self, MainWindow):
                _translate = QtCore.QCoreApplication.translate
                MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
